# ==================================================
# Codecov configuration
# Docs: https://docs.codecov.com/docs/codecov-yaml
# ==================================================

codecov:
  require_ci_to_pass: true
  notify:
    after_n_builds: 1

comment:
  layout: "header, diff, footer"
  behavior: default
  require_changes: true
  max_comments: 1
  show_results: changed
  emoji: true

comment_header: |
  📊 **Codecov Coverage Report**
  Hello @{{author}}! Here's your pull request coverage summary.

comment_footer: |
  🚀 Keep your coverage high — quality matters.
  Full report: [{{build_url}}]

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 1%
        informational: false

    patch:
      default:
        target: 80%
        threshold: 1%
        informational: false

ignore:
  - "docs/**"
  - "scripts/**"
  - "examples/**"
  - "tests/**"
  - "**/*.md"
  - "**/__init__.py"

flags:
  backend:
    paths:
      - "src/**"
  cli:
    paths:
      - "cli/**"
